# Generated by Django 5.2.15 on 2026-07-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nin', models.CharField(db_index=True, max_length=11, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('address', models.TextField()),
                ('state_of_origin', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('relationship', models.CharField(max_length=100)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='riders.rider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('chassis_number', models.CharField(max_length=100, unique=True)),
                ('engine_number', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle', to='riders.rider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
