# Generated by Django 5.2.15 on 2026-07-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rider_photos/'),
        ),
    ]
