# Generated by Django 5.2.15 on 2026-07-22 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_rider_approved_at_rider_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='card_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='rider',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 7, 22, 22, 26, 5, 631197, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='rider_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
