# Generated by Django 5.2.15 on 2026-08-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_rider_card_status_rider_qr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('park', models.CharField(max_length=255)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='riders.rider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
