# Generated by Django 5.2.15 on 2026-08-15 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0005_ridercheckin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('incident_date', models.DateTimeField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='incident_evidence/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('CLOSED', 'Closed')], default='OPEN', max_length=25)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='riders.rider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
