# Generated by Django 5.2.15 on 2026-07-18 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('NIN', 'NIN Slip'), ('LICENSE', "Driver's License"), ('VEHICLE', 'Vehicle Papers'), ('ADDRESS', 'Proof of Address'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='rider_documents/')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='riders.rider')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
